"""Update column names for table Category and Model

Revision ID: 5e515d1b30b7
Revises: 032ba0d36a42
Create Date: 2026-07-22 21:11:14.427286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e515d1b30b7'
down_revision: Union[str, Sequence[str], None] = '032ba0d36a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('object_class', sa.String(), nullable=False))
    op.drop_column('category', 'name')
    op.add_column('model', sa.Column('object_class', sa.String(), nullable=False))
    op.add_column('model', sa.Column('model_name', sa.String(), nullable=False))
    op.drop_column('model', 'name')
    op.drop_column('model', 'checkpoint_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('checkpoint_uri', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('model', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('model', 'model_name')
    op.drop_column('model', 'object_class')
    op.add_column('category', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('category', 'object_class')
    # ### end Alembic commands ###
